import com.rits.ebazar.model.Customer;
import com.rits.ebazar.model.Customer.Category;
import com.rits.ebazar.model.Order;
rule "Classify Customer by order size"
    when
        $o: Order( orderLines.size >= 5, $customer: customer )
        $c: Customer(this == $customer, category == Customer.Category.NA)
    then
        ;
        modify($c){
       	setCategory(Customer.Category.SILVER)
        };
end